import { style } from "@vanilla-extract/css";
import { theme } from "./theme.css";

export const listBox = {
  list: style({
    display: "flex",
    justifyContent: theme.layout.justifyContent.between,
    gap: "24px",
    padding: "20px",
    height: "100%",
    boxSizing: "border-box",
  }),
  item: style({
    position: "relative",
    flex: "1 1 0%",
    padding: "15px",
    height: "100%",
    background: theme.color.gray,
    borderRadius: theme.borderRadius.r7,
    boxSizing: "border-box",
  }),
  itemTitle: style({
    display: "flex",
    alignItems: theme.layout.alignItems.center,
    marginBottom: "20px",
    fontSize: theme.fontSizes.size18,
    fontWeight: "600",
    color: theme.color.navy,
  }),
  itemLength: style({
    marginLeft: "10px",
    padding: "3px 7px",
    fontSize: theme.fontSizes.size14,
    fontWeight: theme.fontWeight.weight400,
    color: theme.color.navy,
    background: theme.color.lightGray,
    borderRadius: theme.borderRadius.r7,
  }),
  itemAdd: style({
    position: "absolute",
    top: "15px",
    right: "15px",
    width: "24px",
    height: "24px",
    textIndent: "-9999px",
    background: `${theme.color.coralBlue} url('../assets/icon_add.png') no-repeat center`,
    border: theme.borderLine.borderNone,
    borderRadius: theme.borderRadius.r50,
    cursor: "pointer",
    transition: "all ease 0.2s",
    ":hover": {
      transform: "rotate(-45deg)",
    },
  }),
  itemRemove: style({
    position: "absolute",
    top: "15px",
    right: "15px",
    width: "24px",
    height: "24px",
    textIndent: "-9999px",
    background: `${theme.color.coralBlue} url('../assets/icon_remove.png') no-repeat center`,
    border: theme.borderLine.borderNone,
    borderRadius: theme.borderRadius.r50,
    cursor: "pointer",
    transition: "all ease 0.2s",
    ":hover": {
      transform: "rotate(-45deg)",
    },
  }),
  addBox: style({
    marginBottom: "15px",
    padding: "10px",
    background: theme.color.deepGray,
    borderRadius: theme.borderRadius.r10,
    boxShadow: theme.boxShadow.small,
  }),
  btnBox: style({
    display: "flex",
    justifyContent: theme.layout.justifyContent.between,
    gap: "8px",
    marginTop: "5px",
  }),
  listWrap: style({
    maxHeight: "calc(100% - 40px)",
    overflowY: "auto",
  }),
  itemList: style({
    position: "relative",
    marginBottom: "15px",
    padding: "20px 48px 20px 20px",
    minHeight: "50px",
    background: theme.color.white,
    borderRadius: theme.borderRadius.r10,
    boxShadow: theme.boxShadow.small,
  }),
  itemText: style({
    position: "relative",
    paddingLeft: "20px",
    whiteSpace: "pre-wrap",
    wordBreak: "break-all",
    fontSize: theme.fontSizes.size15,
    "::before": {
      content: "",
      position: "absolute",
      top: "0",
      left: "0",
      width: "12px",
      height: "16px",
      background: "url('../assets/icon_file.png') no-repeat center",
    },
  }),
};
